import 'package:leage_simulator/entities/club/enum.dart';

const List<Map> englandClubsJson = [
  {
    'name': 'Arsenal',
    'country': Country.england,
    'leagueTier': 1,
    'att': 65,
    'mid': 70,
    'def': 95,
    'playStyle': PlayStyle.pass,
    'homeColor': ClubColor.red,
    'awayColor': ClubColor.yello,
    'fundamental': 10.0,
  },
  {
    'name': 'Villa',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'Aston Villa',
    'att': 65,
    'def': 70,
    'mid': 60,
    'homeColor': ClubColor.purple,
  },
  {
    'name': 'Bournemouth',
    'country': Country.england,
    'leagueTier': 1,
    'att': 35,
    'def': 35,
    'mid': 35,
    'homeColor': ClubColor.red,
  },
  {
    'name': 'Brentford',
    'country': Country.england,
    'leagueTier': 1,
    'att': 55,
    'def': 55,
    'mid': 55,
    'homeColor': ClubColor.red,
  },
  {
    'name': 'Brighton',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'Brighton and Hove Albion',
    'att': 70,
    'def': 70,
    'mid': 70,
    'homeColor': ClubColor.blue,
  },
  {
    'name': 'Burnley',
    'country': Country.england,
    'leagueTier': 1,
    'att': 25,
    'def': 25,
    'mid': 25,
    'attPercent': 0.1,
    'homeColor': ClubColor.purple,
  },
  {
    'name': 'Chelsea',
    'country': Country.england,
    'leagueTier': 1,
    'att': 75,
    'def': 75,
    'mid': 75,
    'homeColor': ClubColor.blue,
    'fundamental': 20.0,
  },
  {
    'name': 'CrystalPalace',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'Crystal Palace',
    'att': 50,
    'def': 50,
    'mid': 50,
    'homeColor': ClubColor.purple,
  },
  {
    'name': 'Everton',
    'country': Country.england,
    'leagueTier': 1,
    'att': 40,
    'mid': 45,
    'def': 40,
    'homeColor': ClubColor.blue,
  },
  {
    'name': 'Fulham',
    'country': Country.england,
    'leagueTier': 1,
    'att': 85,
    'mid': 30,
    'def': 40,
    'homeColor': ClubColor.white,
  },
  {
    'name': 'Liverpool',
    'country': Country.england,
    'leagueTier': 1,
    'att': 100,
    'mid': 75,
    'def': 60,
    'homeColor': ClubColor.deepRed,
    'playStyle': PlayStyle.press,
  },
  {
    'name': 'LutonTown',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'Luton Town',
    'att': 25,
    'def': 25,
    'mid': 25,
    'homeColor': ClubColor.skyBlue,
  },
  {
    'name': 'ManCity',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'Manchester City',
    'att': 90,
    'mid': 80,
    'def': 80,
    'playStyle': PlayStyle.pass,
    'homeColor': ClubColor.skyBlue,
  },
  {
    'name': 'ManU',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'Manchester United',
    'att': 65,
    'mid': 95,
    'def': 55,
    'homeColor': ClubColor.red,
    'fundamental': 20.0,
  },
  {
    'name': 'Newcastle',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'Newcastle United',
    'att': 45,
    'def': 80,
    'mid': 55,
    'homeColor': ClubColor.black,
  },
  {
    'name': 'Nottingham',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'Nottingham Forest',
    'att': 45,
    'def': 45,
    'mid': 45,
    'homeColor': ClubColor.green,
  },
  {
    'name': 'Sheffield',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'Sheffield United',
    'att': 20,
    'def': 20,
    'mid': 25,
    'homeColor': ClubColor.blue,
  },
  {
    'name': 'Tottenham',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'Tottenham Hotspur',
    'att': 90,
    'mid': 65,
    'def': 50,
    'homeColor': ClubColor.white,
  },
  {
    'name': 'WestHam',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'West Ham United',
    'att': 55,
    'def': 50,
    'mid': 55,
    'homeColor': ClubColor.purple,
  },
  {
    'name': 'Wolverhampton',
    'country': Country.england,
    'leagueTier': 1,
    'fullName': 'Wolverhampton Wanderers',
    'att': 70,
    'def': 70,
    'mid': 70,
    'homeColor': ClubColor.orange,
  },
];
